In [0]:
'''
Numpy Library 

'''
import numpy as N

In [2]:
'''
Array Method in numpy 

array() -> used to create multi dimensional arrays

'''
help(N.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [3]:
'''
rank 1 array (1D Numpy array)
'''

ar = N.array([1,2,3,4,5])
print(ar)
print(type(ar))
print(ar[2])
print(ar[2:4])

[1 2 3 4 5]
<class 'numpy.ndarray'>
3
[3 4]


In [4]:
'''
attributes and properties

Shape 
   -> used to check dimension of array
  
dtype 
   -> used to know datatype of array
 
'''
print(ar.shape)
print(ar.dtype)

(5,)
int64


In [5]:
'''
rank 2 matrix
'''

mat = N.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(mat)
print(mat.shape)
print(mat.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
int64


In [6]:
'''
For with numpy arrays
'''
print("Without range method")
for i in ar:
  print(i)
  
print("With range and len methods")
for i in range(len(ar)):
  print(i,':',ar[i])

Without range method
1
2
3
4
5
With range and len methods
0 : 1
1 : 2
2 : 3
3 : 4
4 : 5


In [7]:
'''
Inbuild Method in Numpy

1. zeros 
   -> used to fill array with zeros (float datatype)
   
2. ones
   -> used to fill array with ones (float datatype)
'''

ar = N.zeros(5)
print("One Dimensional Zeroes",ar,sep='\n')

mat = N.ones((2,2))
print("Two Dimensional Ones",mat,sep='\n')

One Dimensional Zeroes
[0. 0. 0. 0. 0.]
Two Dimensional Ones
[[1. 1.]
 [1. 1.]]


In [8]:
'''
Inbuild Method in Numpy

3. full
   -> used to fill an array with constant value
   -> syntax : full((dimension),constantvalue)

'''

ar = N.full(5,6)
mat = N.full((3,3),'abc')

print(ar)
print(mat)

[6 6 6 6 6]
[['abc' 'abc' 'abc']
 ['abc' 'abc' 'abc']
 ['abc' 'abc' 'abc']]


In [9]:
'''
Inbuild Method in Numpy

4. identity
   -> used to create an identity matrix

5. astype
   -> used to change datatype
'''

mat = N.identity(7)
print(mat)

ar = mat.astype(int)
print(ar)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


In [10]:
'''
Inbuild Method in Numpy

6. arange
   -> used to generate range of integer values similar to range
   
7. linspace
   -> divides a group into evenly spaced intervals
   -> by default 50 groups are created in given range
   
'''

print(N.arange(10))
print(N.arange(1,11))
print(N.arange(2,50,2))
print(N.arange((10),dtype='float'))

print(N.linspace(1,50))
print(N.linspace(1,100,num=5))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]
[  1.    25.75  50.5   75.25 100.  ]


In [11]:
'''
Inbuild Method in Numpy

8. reshape
   -> changes the dimension of an array

'''
ar = N.array([1,2,3,4,5,6,7,8,9])
print(ar.reshape(3,3))
print(N.arange(1,28).reshape(3,3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [12]:
'''
Inbuild Method in random class generally used with numpy

1. random
   -> used to fill an array with random values between 0 and 1
   
2. randint
   -> used to fill random within a given range
   
'''

ar = N.random.random()
mat = N.random.randint(1,101, size=(3,3))

print(ar)
print(mat)

0.1155325687892399
[[91 67  5]
 [97 38 73]
 [92 59 15]]


In [13]:
'''
Datatypes in Numpy 1

'''

iar = N.array([1,2,3,4,5])
far = N.array([1.,2.,3.,4.,5.])
car = N.array(['a','b','c','d','e'])
sar = N.array(['abc','bcd','cde'])

print(iar.dtype)
print(far.dtype)
print(car.dtype)
print(sar.dtype)

int64
float64
<U1
<U3


In [14]:
'''
Datatypes in Numpy 2
'''

iar = N.array([1,2,3,4,5],dtype='float32')
far = N.array([10.,20.,30.,40.,50.],dtype=N.int)
ar = N.zeros((2,2),dtype=int)

print(iar.dtype)
print(iar)

print(far.dtype)
print(far)

print(ar.dtype)
print(ar)

float32
[1. 2. 3. 4. 5.]
int64
[10 20 30 40 50]
int64
[[0 0]
 [0 0]]


In [15]:
'''
Numpy Broadcasting

rules to be performed while performing operations on arrays
1. either arrays should be of same size
2. or one array must be of size 1

'''

a = N.array([1,2,3])
b = N.array([2,2,2])
c = N.array([3])

print(a*b)
print(a*c)

m1 = N.array([[1,2],[3,4]])
m2 = N.array([[2,2],[2,2]])

print(m1+m2)
print(m2-c)

m3 = N.array([10,100])

print(m1*m3)

[2 4 6]
[3 6 9]
[[3 4]
 [5 6]]
[[-1 -1]
 [-1 -1]]
[[ 10 200]
 [ 30 400]]
